apps/sharefile/urls.py
# _*_ coding: utf-8 _*_
_author_ = 'Ace'
_date_ = '2019-01-08 10:16'

from sharefile.view import AddfileView,FileListView,ButtonsView,EditView,WheelView,CountDownloadView
from django.urls import path, include, re_path
# from . import views


app_name = 'users'


urlpatterns = [
        path('addfile/', AddfileView.as_view(), name='addfile'),
        path('filelist/', FileListView.as_view(), name='filelist'),
        # re_path('filelist/(?P<pk>\d+)/',FileListView.as_view(), name='filelist'),
        re_path('filedownload/(?P<product_id>\d+)/', CountDownloadView.as_view, name='countdownload'),
        path('buttons/', ButtonsView.as_view(), name='buttons'),
        path('edit/', EditView.as_view(), name='edit'),
        path('wheel/', WheelView.as_view(), name='wheel'),
        #删除
        # path(r'^del-file/$', views.del_file, name="del_file"),
        # path('delete_file/',views.del_file, name='delete_file'),
        ]

crm/urls.py
from django.urls import path, include, re_path
# 用于设定图片URL地址
from django.views.static import serve

import xadmin
# 配件添加图片URL时用到的
from apps.users.views.ActiveUserView import ActiveUserView
from apps.users.views.ForgetPwdView import ForgetPwdView
from apps.users.views.Index import Index
from apps.users.views.LoginView import LoginView
from apps.users.views.LogoutView import LogoutView
from apps.users.views.ModifyPwdView import ModifyPwdView
from apps.users.views.RegisterView import RegisterView
from apps.users.views.ResetView import ResetView
from .settings import MEDIA_ROOT

# from users.views import user_login,LoginView,RegisterView,ActiveUserView,ForgetPwdView,ResetView,ModifyPwdView,LogoutView

urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    re_path(r'^$', Index.as_view(), name="index"),
    # 基于类方法实现登录,这里是调用它的方法
    # path('', LoginView.as_view(), name="login"),
    # path('index/',TemplateView.as_view(''),name="index"),
    path('index/', Index.as_view(), name="index"),
    path('login/', LoginView.as_view(), name="login"),
    path('register/', RegisterView.as_view(), name="register"),
    # 验证码url
    path("captcha/", include('captcha.urls')),
    # 激活用户url
    re_path('active/(?P<active_code>.*)/', ActiveUserView.as_view(), name="user_active"),

    # 忘记密码
    path('forget/', ForgetPwdView.as_view(), name="forget_pwd"),
    # 重置密码urlc ：用来接收来自邮箱的重置链接, 用于在邮箱里面点击后，所要跳转到的页面链接
    re_path('reset/(?P<active_code>.*)/', ResetView.as_view(), name="reset_pwd"),
    # 修改密码url; 用于passwordreset页面提交表单, 用于点击来链接里面提交密码。
    path('modify_pwd/', ModifyPwdView.as_view(), name="modify_pwd"),

    # sharefile的URL
    path("sharefile/", include('sharefile.urls', namespace='sharefile')),

    # users的URL
    path("users/", include('users.urls', namespace='users')),

    # 处理图片显示的url,使用Django自带serve,传入参数告诉它去哪个路径找，我们有配置好的路径MEDIAROOT， 其中document_root是一个固定写法。
    re_path('media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),

    path('logout/', LogoutView.as_view(), name='logout'),

    # path('profile/',ProfileView.as_view(),name='profile'),

]

apps/users/forms/LoginForm.py
# _*_ coding: utf-8 _*_
# 引入Django表单
from  django import forms

# 登录表单验证
class LoginForm(forms.Form):
    # 用户名密码不能为空
    username = forms.CharField(required=True)
    # 密码不能小于5位
    password = forms.CharField(required=True, min_length=5)

apps/users/forms/RegisterForm.py
# _*_ coding: utf-8 _*_
# 引入Django表单
from captcha.fields import CaptchaField
from  django import forms

# 验证码form & 注册表单form
class RegisterForm(forms.Form):
    # 此处email与前端name需保持一致。
    email = forms.EmailField(required=True)
    # 密码不能小于5位
    password = forms.CharField(required=True, min_length=5)
    # 应用验证码 自定义错误输出key必须与异常一样
    captcha = CaptchaField(error_messages={"invalid": u"验证码错误"})

apps/users/views/LoginView.py
# _*_ coding: utf-8 _*_
from django.contrib.auth import login, authenticate
from django.http import HttpResponseRedirect
from django.shortcuts import render

# 基于类实现需要继承的view
from django.urls import reverse
from django.views.generic.base import View

from users.forms import LoginForm

from users.models import Permission, UserProfile

from django.core import serializers


class LoginView(View):
    # 直接调用get方法免去判断
    def get(self, request):
        # render就是渲染html返回用户
        # render三变量: request 模板名称 一个字典写明传给前端的值
        redirect_url = request.GET.get('next', '')
        return render(request, "login.html", {
            "redirect_url": redirect_url
        })

    def post(self, request):
        # 类实例化需要一个字典参数dict:request.POST就是一个QueryDict所以直接传入
        # POST中的usernamepassword，会对应到form中
        login_form = LoginForm(request.POST)
        # 默认false
        request.session["is_login"] = False
        # is_valid判断我们字段是否有错执行我们原有逻辑，验证失败跳回login页面
        if login_form.is_valid():
            # 取不到时为空，username，password为前端页面name值
            user_name = request.POST.get("username", "")
            pass_word = request.POST.get("password", "")
            print("user_name", user_name, "pass_word", pass_word)
            # 成功返回user对象,失败返回null
            user = authenticate(username=user_name, password=pass_word)
            # print("user: ", user.is_active)
            print("user:", user)
            print(UserProfile.objects.filter(email=user_name))
            print("*" * 20)
            # 如果不是null说明验证成功
            if user is not None:
                # 只有当用户激活时才给登录
                # if user.is_active:
                if True:
                    # login_in 两参数：request, user
                    # 实际是对request写了一部分东西进去，然后在render的时候：
                    # request是要render回去的。这些信息也就随着返回浏览器。完成登录
                    login(request, user)
                    # 跳转到首页 user request会被带回到首页
                    # 存入session 序列化用户对象
                    user_dict = {}
                    user_ser = UserProfile.objects.filter(email=user_name)[0]
                    user_dict["is_admin"] = user_ser.is_admin
                    user_dict["user_name"] = user_ser.username
                    request.session["user"] = user_dict
                    request.session["is_login"] = True
                    # 增加重定向回原网页。
                    redirect_url = request.POST.get('next', '')

                    if redirect_url:
                        return HttpResponseRedirect(redirect_url)
                    # 跳转到首页 user request会被带回到首页
                    return HttpResponseRedirect(reverse("index"))
                # 即用户未激活跳转登录，提示未激活
                else:
                    return render(
                        request, "login.html", {
                            "msg": "用户名未激活! 请前往邮箱进行激活"})
            # 仅当用户真的密码出错时
            else:
                return render(request, "login.html", {"msg": "用户名或密码错误!"})
        # 验证不成功跳回登录页面
        # 没有成功说明里面的值是None，并再次跳转回主页面
        else:
            return render(
                request, "login.html", {
                    "login_form": login_form})

apps/users/views/RegisterView.py
# _*_ coding: utf-8 _*_
from django.contrib.auth.hashers import make_password
from django.shortcuts import render

from users.forms.RegisterForm import RegisterForm

# 基于类实现需要继承的view
from django.views.generic.base import View

from users.models.UserProfile import UserProfile
from utils.email_send import send_register_eamil


class RegisterView(View):
    # get方法直接返回页面
    def get(self, request):
        # 添加验证码
        register_form = RegisterForm()
        return render(
            request, "register.html", {
                'register_form': register_form})

    def post(self, request):
        # 实例化form
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            # 这里注册时前端的name为email
            user_name = request.POST.get("email", "")
            print("-"*50)
            print("user_name", user_name)
            print("-" * 50)
            # 用户查重
            if UserProfile.objects.filter(email=user_name):
                return render(
                    request, "register.html", {
                        "register_form": register_form, "msg": "用户已存在"})
            pass_word = request.POST.get("password", "")

            # 实例化一个user_profile对象，将前台值存入
            user_profile = UserProfile()
            user_profile.username = user_name
            user_profile.email = user_name

            # 默认激活状态为false
            user_profile.is_active = False

            # 加密password进行保存
            user_profile.password = make_password(pass_word)
            user_profile.save()

            # 写入欢迎注册消息
            # user_message = UserMessage()
            # user_message.user = user_profile.id
            # user_message.message = "欢迎注册CRM!! --系统自动消息"
            # user_message.save()
            # 发送注册激活邮件
            send_register_eamil(user_name, "register")

            # 跳转到登录页面
            return render(request, "login.html", )
        # 注册邮箱form验证失败
        else:
            return render(
                request, "register.html", {
                    "register_form": register_form})

templates/Ace-dashboard-table-basic.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="row">
                <!-- column -->
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">最新下载统计</h4>
                            {#                                <h6 class="card-subtitle">Add<code>.table-bordered</code>for borders on all sides of the table and cells.</h6>#}
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead>
                                    <tr>
                                        <th>文件名称</th>
                                        <th>下载数量</th>
                                        <th>上传时间</th>
                                        <th class="text-nowrap">描述</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for file in allfile %}
                                        <tr>
                                            <td>{{ file.models_Filename }}</td>
                                            <td>
                                                <div class="progress progress-xs margin-vertical-10 ">
                                                    <div class="progress-bar bg-danger"
                                                         style="width: 35%; height:6px;"></div>
                                                </div>
                                            </td>
                                            <td>{{ file.models_Updated_date }}</td>
                                            <td class="text-nowrap">
                                                {{ file.models_Filedes }}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- column -->
                <!-- column -->
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">最新上载统计</h4>

                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>文件名称</th>
                                        <th>上传者</th>
                                        <th>上传日期</th>
                                        <th>用于</th>
                                        <th>部门</th>
                                        <th>描述</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for file in allfile %}
                                        <tr>
                                            <td>{{ file.models_Filename }}</td>
                                            <td>Ace</td>
                                            <td><span class="text-muted"><i
                                                    class="fa fa-clock-o"></i>{{ file.models_Updated_date }}</span></td>
                                            <td>{{ file.models_Fileusedfor }}</td>
                                            <td>
                                                <div class="label label-table label-success">{{ file.models_Filedepartment }}</div>
                                            </td>
                                            <td>{{ file.models_Filedes }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- column -->
            </div>
{% endblock %}
{% block bread %}
<li class="breadcrumb-item active">Deshboard</li>
{% endblock %}

templates/Ace-file-add-realestate-add-property.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block bread %}文件列表{% endblock %}
{% block content %}
  <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <form action="{% url 'sharefile:addfile' %}" class="pro-add-form" method="post" enctype="multipart/form-data">
                                    <div class="form-group">
                                        <label for="plocation">文件名称</label>
                                        <input name="filename" type="text" class="form-control" id="plocation" placeholder="文件名称"> </div>
                                    <div class="form-group">
                                        <label for="pname">使用部门</label>

                                            <select name="filedepartment" class="form-control custom-select" id="city">
                                                {% for deptfile in dept  %}
                                                <option >{{ deptfile.Department_name }}</option>
                                                {% endfor %}
                                            </select>

                                        <label for="pdesc">文件描述</label>
                                        <textarea name="filedes" class="form-control" rows="5" id="pdesc" placeholder="文件描述"></textarea>
                                    </div>
                                    <h5 class="card-title">Upload file</h5>

                                    <div class="form-group">
                                        <label class="control-label">文件用于</label>
                                            <select name="fileusedfor" class="form-control custom-select" id="city">
                                                {% for usefilefor in usedfor  %}
                                                <option>{{ usefilefor.Usedfor }}</option>
                                                {% endfor %}
                                            </select>
                                    </div>
                                    <div class="form-group">
                                        <label for="input-file-now">上传文件</label>
                                        <input name="fileupload" type="file" id="input-file-now" class="dropify" />
                                    </div>
                                    <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">添加文件</button>
                                    <button type="submit" class="btn btn-dark waves-effect waves-light">取消</button>
                                {% csrf_token %}
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
{% endblock %}

{% block custom_js %}
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="{% static 'node_modules/jquery/jquery-3.2.1.min.js' %}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{% static 'node_modules/popper/popper.min.js' %}"></script>
    <script src="{% static 'node_modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="{% static 'js/perfect-scrollbar.jquery.min.js' %}"></script>
    <!--Wave Effects -->
    <script src="{% static 'js/waves.js' %}"></script>
    <!--Menu sidebar -->
    <script src="{% static 'js/sidebarmenu.js' %}"></script>
    <!--Custom JavaScript -->
    <script src="{% static 'js/custom.min.js' %}"></script>
    <!-- This Page JS -->
    <script src="{% static 'node_modules/inputmask/dist/min/jquery.inputmask.bundle.min.js' %}"></script>
    <script src="{% static 'js/pages/mask.init.js' %}"></script>
    <script src="{% static 'node_modules/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.js' %}" type="text/javascript"></script>
    <!-- jQuery file upload -->
    <script src="{% static 'node_modules/dropify/dist/js/dropify.min.js' %}"></script>
    <script>
    $("input[name='tch1']").TouchSpin();
    $("input[name='tch2']").TouchSpin();
    $("input[name='tch3']").TouchSpin();
    $("input[name='tch4']").TouchSpin();
    $("input[name='tch5']").TouchSpin();
    $('.dropify').dropify();
    </script>
    <script type="text/javascript">
    jQuery.browser = {};
    (function() {
        jQuery.browser.msie = false;
        jQuery.browser.version = 0;
        if (navigator.userAgent.match(/MSIE ([0-9]+)\./)) {
            jQuery.browser.msie = true;
            jQuery.browser.version = RegExp.$1;
        }
    })();
    </script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
{% block head %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon.png' %}">
    <title>SZTU Sharing system</title>
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'node_modules/dropify/dist/css/dropify.min.css' %}">
    <link href="{% static 'node_modules/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
{% endblock %}

<body class="skin-blue fixed-layout">
<!-- ============================================================== -->
<!-- Preloader - style you can find in spinners.css -->
<!-- ============================================================== -->
{#<div class="preloader">#}
{#    <div class="loader">#}
{#        <div class="loader__figure"></div>#}
{#        <p class="loader__label">SZTU sharing system...</p>#}
{#    </div>#}
{#</div>#}
<!-- ============================================================== -->
<!-- Main wrapper - style you can find in pages.scss -->
<!-- ============================================================== -->
<div id="main-wrapper">
    <!-- ============================================================== -->
    <!-- Topbar header - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <header class="topbar">
        <nav class="navbar top-navbar navbar-expand-md navbar-dark">
            <!-- ============================================================== -->
            <!-- Logo -->
            <!-- ============================================================== -->
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'index' %}">
                    <!-- Logo icon --><b>
                    <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                    <!-- Dark Logo icon -->
                    <img src="{% static 'images/logo-icon.png' %}" alt="homepage" class="dark-logo"/>
{#                    <!-- Light Logo icon -->#}
{#                    <img src="{% static 'images/logo-light-icon.png' %}" alt="homepage" class="light-logo"/>#}
                    </b>
                    <!--End Logo icon -->
                    <!-- Logo text -->
                         <!-- dark Logo text -->
                         <img src="{% static 'images/logo-text.png' %}" alt="homepage" class="dark-logo"/>
                    <!-- Light Logo text -->
{#                         <img src="{% static 'images/logo-light-text.png' %}" class="light-logo" alt="homepage"/></span>#}
                </a>
            </div>
            <!-- ============================================================== -->
            <!-- End Logo -->
            <!-- ============================================================== -->

        </nav>
    </header>
    <!-- ============================================================== -->
    <!-- End Topbar header -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Left Sidebar - style you can find in sidebar.scss  -->
    <!-- ============================================================== -->
    <aside class="left-sidebar">
        <!-- Sidebar scroll-->
        <div class="scroll-sidebar">
            <!-- User Profile-->
            <div class="user-profile">

                {% if request.user.is_authenticated %}
{#                如果登陆后#}
                <div class="user-pro-body">
                    <div><img src="{% static 'images/users/2.jpg' %}" alt="user-img" class="img-circle"></div>
                    <div class="dropdown">
                        <a href="javascript:void(0)" class="dropdown-toggle u-dropdown link hide-menu"
                           data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ace<span class="caret"></span></a>
                        <div class="dropdown-menu animated flipInY">

{#                            <!-- text-->#}
                            <a href="#" class="dropdown-item"><i class="ti-user"></i>个人中心</a>

                            <div class="dropdown-divider"></div>
                            <!-- text-->
                            <a href="{% url 'logout' %}" class="dropdown-item"><i class="fa fa-power-off"></i>登出</a>
{#                            <a href="Ace-pages-profile.html" class="dropdown-item"><i class="fa fa-power-off"></i>prfile</a>#}
                            <!-- text-->
                        </div>
                    </div>
                </div>
{#                登陆前#}
                {% else %}
                <div class="1">
                    <div><a href="{% url 'login' %}">--------------  登陆  -------------</a></div>
                </div>
                {% endif %}

            </div>
            <!-- Sidebar navigation-->
            <nav class="sidebar-nav">
                <ul id="sidebarnav">
                    <li class="nav-small-cap">--- 导航信息</li>
                    <li><a class="has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i
                            class="icon-speedometer"></i><span class="hide-menu">展示</span></a>
                        <ul aria-expanded="false" class="collapse">
                            <li><a href="{% url 'index' %}">主页</a></li>

                        </ul>
                    </li>
                    <li><a class="has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i
                            class="ti-bar-chart-alt"></i><span class="hide-menu">文件</span></a>
                        <ul aria-expanded="false" class="collapse">
                            <li><a href="{% url 'sharefile:filelist' %}">文件列表</a></li>

                            {% if request.session.user.is_admin == 1 %}
                                <li><a href="{% url 'sharefile:addfile' %}">文件上传</a></li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
            </nav>
            <!-- End Sidebar navigation -->
        </div>
        <!-- End Sidebar scroll-->
    </aside>
    <!-- ============================================================== -->
    <!-- End Left Sidebar - style you can find in sidebar.scss  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Page wrapper  -->
    <!-- ============================================================== -->
    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h4 class="text-themecolor">统计页面</h4>
                </div>
                <div class="col-md-7 align-self-center text-right">
                    <div class="d-flex justify-content-end align-items-center">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
                            {% block bread %}

                            {% endblock %}
                        </ol>
                        {% if request.session.user.is_admin == 1 %}
                            <button type="button" class="btn btn-dark d-none d-lg-block m-l-15"><i
                                    class="fa fa-plus-circle"></i><a href="{% url 'sharefile:addfile' %}">上传文件</a>
                            </button>
                        {% endif %}
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
        {% block content %}

        {% endblock %}
        </div>
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Page wrapper  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer">
        Shenzhen Technology University
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
</div>
<!-- ============================================================== -->
<!-- End Wrapper -->
<!-- ============================================================== -->
<!-- ============================================================== -->
<!-- All Jquery -->
<!-- ============================================================== -->\
{% block custom_js %}
    <script src="{% static 'node_modules/jquery/jquery-3.2.1.min.js' %}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{% static 'node_modules/popper/popper.min.js' %}"></script>
    <script src="{% static 'node_modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="{% static 'js/perfect-scrollbar.jquery.min.js' %}"></script>
    <!--Wave Effects -->
    <script src="{% static 'js/waves.js' %}"></script>
    <!--Menu sidebar -->
    <script src="{% static 'js/sidebarmenu.js' %}"></script>
    <!--stickey kit -->
    <script src="{% static 'node_modules/sticky-kit-master/dist/sticky-kit.min.js' %}"></script>
    <script src="{% static 'node_modules/sparkline/jquery.sparkline.min.js' %}"></script>
    <!--Custom JavaScript -->
    <script src="{% static 'js/custom.min.js' %}"></script>
    <!-- jQuery peity -->
    <script src="{% static 'node_modules/peity/jquery.peity.min.js' %}"></script>
    <script src="{% static 'node_modules/peity/jquery.peity.init.js' %}"></script>
{% endblock %}
</body>

</html>